[tool.poetry]
name = "nhsa"
version = "0.1.0"
description = ""
authors = ["bamacgabhann <127785144+breandan.macgabhann@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
